  spring:
    messages:
      basename: label, utility-error, error
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
        - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

  server:
    servlet:
      context-path: /screentwo